import app from './App.js';
import selectionSort from './SelectionSort.js';
import bubbleSort from './BubbleSort.js';
import insertionSort from './InsertionSort.js';
import quickSort1 from './QuickSort1.js';
import quickSort2 from './QuickSort2.js';
import quickSort3 from './QuickSort3.js';
import mergeSort from './MergeSort.js';
import radixSort from './RadixSort.js';
app.addAlgorithm('ss', selectionSort);
app.addAlgorithm('bs', bubbleSort);
app.addAlgorithm('is', insertionSort);
app.addAlgorithm('qs1', quickSort1);
app.addAlgorithm('qs2', quickSort2);
app.addAlgorithm('qs2', quickSort3);
app.addAlgorithm('ms', mergeSort);
app.addAlgorithm('rs', radixSort);
app.run();